### ISSUE TITLE
Missing dependency 'mosek' and 'cplex'

### ISSUE THREAD

**Issue by JerryLife** [khtae8250/iFlipper#3]
After installation, `bash run.sh` failed because of missing module `mosek`. `pip install mosek` solved this issue. Please update the README for illustration.

**Comment by JerryLife** [comment]
Another requirement is missing from README `cplex`. `pip install cplex` solved this issue.

**Comment by jyparkkr** [comment]
In order to set up Mosek and Cplex, it's important to follow to the guidelines outlined in the [instructions](https://github.com/khtae8250/iFlipper#license-for-optimization-solver). Given that these programs aren't freely available, installing the complete software via pip isn't feasible.

**Comment by JerryLife** [comment]
Thank you for the prompt reply. This issue has resolved after I reinstalling cplex according to the given link.
